# Server
server.port=${PORT:8080}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database
spring.datasource.url=${MYSQL_PUBLIC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Swagger
springdoc.swagger-ui.path=/swagger-ui/index.html

# JWT
tuan.jwt.base64-secret=${JWT_SECRET}
tuan.jwt.access-token-validity-in-seconds=5000
tuan.jwt.refresh-token-validity-in-seconds=86400

# Upload
tuan.upload-file.basepath=/data/uploads/

# Pagination
spring.data.web.pageable.one-indexed-parameters=true

# File upload limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# AWS S3
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_BUCKET}
####
vnpay:
    pay-url: ${PAY_URL}
    return-url:${RETURN_URL}
    tmn-code: ${TMN_CODE}
    secret-key: ${SECRET_KEY}
    api-url: ${API_URL}